# __main__.py
#
# Copyright (C) 2019 GabMus
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import pathlib
import json

import argparse
from gi.repository import Gtk, Wnck, Gdk, Gio, GdkPixbuf

from . import wallpaper_merger as WallpaperMerger
from . import threading_helper as ThreadingHelper
from .confManager import ConfManager
from .app_window import HydraPaperAppWindow

class Application(Gtk.Application):
    def __init__(self, **kwargs):
        super().__init__(
            application_id = 'org.gabmus.hydrapaper',
            flags = Gio.ApplicationFlags.HANDLES_COMMAND_LINE,
            **kwargs
        )
        self.confman = ConfManager()
        self.window = HydraPaperAppWindow()

        # Lock when refreshing wallpapers to avoid duplicates generated by spam presses
        self.wallpapers_refreshing_locked = False

    def on_about_activate(self, *args):
        about_builder = Gtk.Builder.new_from_resource(
            '/org/gabmus/hydrapaper/aboutdialog.glade'
        )
        dialog = about_builder.get_object('aboutdialog')
        dialog.set_modal(True)
        dialog.set_transient_for(self.window)
        dialog.present()

    def all_wallpaper_folder_interactives_set_sensitive(self, sensitive):
        # listbox
        # --> listboxrow []
        #     --> box
        #         --> checkbutton
        #         --> label
        #         --> button
        for child in self.wallpapers_folders_popover_listbox.get_children():
            for subchild in child.get_child().get_children():
                if type(subchild) in [Gtk.CheckButton, Gtk.Button]:
                    subchild.set_sensitive(sensitive)
        self.add_to_favorites_toggle.set_sensitive(sensitive)
        self.builder.get_object('addWallpapersPath').set_sensitive(sensitive)
        self.on_wallpapersFoldersPopoverListbox_row_selected(
            self.wallpapers_folders_popover_listbox,
            self.wallpapers_folders_popover_listbox.get_selected_row()
        )


    def on_wallpaper_folder_switch_toggled(self, check, state):
        if not check.value:
            return
        c_wallpapers_paths = self.gmconfig_man.get('wallpapers_paths')
        for index, folder in enumerate(c_wallpapers_paths):
            if folder['path'] == check.value:
                c_wallpapers_paths[index]['active'] = check.get_active()
                self.gmconfig_man.set('wallpapers_paths', c_wallpapers_paths)
                break
        #self.refresh_wallpapers_flowbox()
        self.show_hide_wallpapers()

    def refresh_wallpapers_flowbox(self):
        if self.wallpapers_refreshing_locked:
            return
        self.wallpapers_refreshing_locked = True
        self.all_wallpaper_folder_interactives_set_sensitive(False)
        self.empty_wallpapers_flowbox()
        
        get_wallpapers_thread = ThreadingHelper.do_async(self.get_wallpapers_list, (0,))
        ThreadingHelper.wait_for_thread(get_wallpapers_thread)
        self.fill_wallpapers_flowbox()
        self.show_hide_wallpapers()
        self.wallpapers_refreshing_locked = False
        self.all_wallpaper_folder_interactives_set_sensitive(True)

    def do_before_activate(self):
        self.fill_monitors_flowbox()
        self.fill_wallpapers_folders_popover_listbox()

    def apply_from_cli(self, wlist_cli):
        # check all the passed wallpapers to be correct
        if len(wlist_cli) < len(self.monitors):
            print(
                'Error: you passed {0} wallpapers for {1} monitors'.format(
                    len(wlist_cli), len(self.monitors)
                )
            )
            exit(1)
        for wpath in wlist_cli:
            if not self.check_if_image(wpath):
                print('Error: {0} is not a valid image path'.format(wpath))
                exit(1)
        for monitor, n_wp in zip(self.monitors, wlist_cli):
            monitor.wallpaper = n_wp
        self.dump_monitors_to_config()
        self.apply_button_async_handler(self.monitors)

    def do_activate(self):
        if self.args and self.args.wallpaper_path:
            print(self.monitors)
            self.apply_from_cli(self.args.wallpaper_path[0])
            self.quit()
            exit(0)
        super().do_activate()
        self.window.show_all()

    def do_command_line(self, *args):
        """
        GTK.Application command line handler
        called if Gio.ApplicationFlags.HANDLES_COMMAND_LINE is set.
        must call the self.do_activate() to get the application up and running.
        """
        Gtk.Application.do_command_line(self, *args)  # call the default commandline handler
        # make a command line parser
        parser = argparse.ArgumentParser()
        parser.add_argument('-c', '--cli', dest='wallpaper_path', nargs='+', action='append', help='set wallpapers from command line')
        # parse the command line stored in args, but skip the first element (the filename)
        self.args = parser.parse_args(args.get_arguments()[1:])
        # call the main program do_activate() to start up the app
        self.do_activate()
        return 0

    def apply_button_async_handler(self, monitors):
        desktop_environment = os.environ.get('XDG_CURRENT_DESKTOP')
        if desktop_environment == 'MATE':
            wp_setter_func = WallpaperMerger.set_wallpaper_mate
        else:
            wp_setter_func = WallpaperMerger.set_wallpaper_gnome
        if len(monitors) == 1:
            wp_setter_func(monitors[0].wallpaper, 'zoom')
            return
        if not os.path.isdir(HYDRAPAPER_CACHE_PATH):
            os.mkdir(HYDRAPAPER_CACHE_PATH)
        new_wp_filename = '_'.join(([m.__repr__() for m in monitors]))
        saved_wp_path = '{0}/{1}.png'.format(HYDRAPAPER_CACHE_PATH, hashlib.sha256(
            'HydraPaper{0}'.format(new_wp_filename).encode()
        ).hexdigest())
        if not os.path.isfile(saved_wp_path):
            WallpaperMerger.multi_setup_pillow(
                monitors,
                saved_wp_path
            )
        else:
            print(
                'Hit cache for wallpaper {0}. Skipping merge operation.'.format(
                    saved_wp_path
                )
            )
        wp_setter_func(saved_wp_path)

    def on_applyButton_clicked(self, btn):
        for m in self.monitors:
            if not m.wallpaper:
                print('Set all of the wallpapers before applying')
                self.errorDialog.set_markup('Set all of the wallpapers before applying')
                self.errorDialog.run()
                self.errorDialog.hide()
                return
        # disable interaction
        self.apply_button.set_sensitive(False)
        self.monitors_flowbox.set_sensitive(False)
        self.wallpapers_flowbox.set_sensitive(False)
        # activate spinner
        self.apply_spinner.show()
        self.apply_spinner.start()
        # run thread
        thread = ThreadingHelper.do_async(self.apply_button_async_handler, (self.monitors[:],))
        # wait for thread to finish
        ThreadingHelper.wait_for_thread(thread)
        # restore interaction and deactivate spinner
        self.apply_button.set_sensitive(True)
        self.monitors_flowbox.set_sensitive(True)
        self.wallpapers_flowbox.set_sensitive(True)
        self.apply_spinner.stop()
        self.apply_spinner.hide()
        self.dump_monitors_to_config()

    def on_wallpapersFoldersToggle_toggled(self, toggle):
        if toggle.get_active():
            self.wallpapers_folders_popover.popup()
        else:
            self.wallpapers_folders_popover.popdown()

    # Handler functions END

def main():
    application = Application()

    try:
        ret = application.run(sys.argv)
    except SystemExit as e:
        ret = e.code

    sys.exit(ret)


if __name__ == '__main__':
    main()
