# __main__.py
#
# Copyright (C) 2019 GabMus
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import argparse
from gi.repository import Gtk, Gio
from .confManager import ConfManager
from .app_window import HydraPaperAppWindow
from .is_image import is_image
from .monitor_parser import build_monitors_from_gdk

class Application(Gtk.Application):
    def __init__(self, **kwargs):
        super().__init__(
            application_id = 'org.gabmus.hydrapaper',
            flags = Gio.ApplicationFlags.HANDLES_COMMAND_LINE,
            **kwargs
        )
        self.confman = ConfManager()
        self.window = HydraPaperAppWindow()

        # Lock when refreshing wallpapers to avoid duplicates generated by spam presses
        self.wallpapers_refreshing_locked = False

    def on_about_activate(self, *args):
        about_builder = Gtk.Builder.new_from_resource(
            '/org/gabmus/hydrapaper/aboutdialog.glade'
        )
        dialog = about_builder.get_object('aboutdialog')
        dialog.set_modal(True)
        dialog.set_transient_for(self.window)
        dialog.present()

    def apply_from_cli(self, wlist_cli):
        # check all the passed wallpapers to be correct
        monitors = build_monitors_from_gdk()
        if len(wlist_cli) < len(monitors):
            print(
                'Error: you passed {0} wallpapers for {1} monitors'.format(
                    len(wlist_cli), len(monitors)
                )
            )
            exit(1)
        for wpath in wlist_cli:
            if not is_image(wpath):
                print('Error: {0} is not a valid image path'.format(wpath))
                exit(1)
        for monitor, n_wp in zip(monitors, wlist_cli):
            monitor.wallpaper = n_wp
        n_monitors = {}
        for m in monitors:
            n_monitors[m.name] = m.wallpaper
        self.confman.conf['monitors'] = n_monitors
        self.confman.save_conf()
        self.apply_button_async_handler(monitors)

    def do_activate(self):
        if self.args and self.args.wallpaper_path:
            print(self.monitors)
            self.apply_from_cli(self.args.wallpaper_path[0])
            self.quit()
            exit(0)
        super().do_activate()
        self.window.show_all()

    def do_command_line(self, *args):
        """
        GTK.Application command line handler
        called if Gio.ApplicationFlags.HANDLES_COMMAND_LINE is set.
        must call the self.do_activate() to get the application up and running.
        """
        Gtk.Application.do_command_line(self, *args)  # call the default commandline handler
        # make a command line parser
        parser = argparse.ArgumentParser()
        parser.add_argument('-c', '--cli', dest='wallpaper_path', nargs='+', action='append', help='set wallpapers from command line')
        # parse the command line stored in args, but skip the first element (the filename)
        self.args = parser.parse_args(args.get_arguments()[1:])
        # call the main program do_activate() to start up the app
        self.do_activate()
        return 0

def main():
    application = Application()

    try:
        ret = application.run(sys.argv)
    except SystemExit as e:
        ret = e.code

    sys.exit(ret)


if __name__ == '__main__':
    main()
